log_format: '[%(name)s][%(asctime)s][%(lineno)3d][%(levelname)7s] %(message)s'
date_time_format: '%m-%d %H:%M:%S'
log_level: 'DEBUG'

sspanel_url: 'https://panel.ss.com'

test_url: 'http://gd.189.cn'
test_time: 10
delay_sample: 43200

diff_time: 10
post_load_period: 60
upload_throughput_period: 600
post_delay_standard_period: 129600

manager_address: '/var/run/shadowsocks-manager.sock'
bind_address: '/tmp/shadowsocks-munager.sock'

fast_open: true
mode: 'tcp_and_udp'
