log_format: '[%(asctime)s][%(lineno)3d][%(levelname)s] %(message)s'
date_time_format: '%m-%d %H:%M:%S'
log_level: 'DEBUG'

sspanel_url: 'https://panel.ss.com'
key: 'this_is_mu_key'
node_id: 14

upload_throughput_period: 60
update_port_period: 60

manager_address: '/var/run/shadowsocks-manager.sock'
bind_address: '/tmp/shadowsocks-munager.sock'

fast_open: true
mode: 'tcp_and_udp'
